"""add age column to users table

Revision ID: 906ffd5a0ff5
Revises: 8b66834003bf
Create Date: 2023-05-16 16:35:20.516240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906ffd5a0ff5'
down_revision = '8b66834003bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
